title: Pranati Shete # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 A final year BE student, highly motivated software engineer with strong learning abilities!
  <br><br>
 I primarily use <strong> Python </strong>, but picking up a new framework or language isn't a problem.
  <br><br>
 Over the course of my studies, I am constantly updating myself with the skills required to be <strong>Software Engineer</strong>.
  <br><br>
  Currently I am learning NLP techniques with deep learning for my final year project with my constant learning and application I will easily adjust with the workflow of a company and deliver the best I can. 
  <br><br>
  <a href="https://www.linkedin.com/in/pranati-shete-9936b613b">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
